module Common {
    struct Vector3D {
      float x;
      float y;
      float z;
    };  

    struct Quaternion {
      float x;
      float y;
      float z;
      float w;
    };

    struct Pose3D {
      Vector3D translation;
      Quaternion rotation;
    };

    struct Pose3DTimestamped {
      double timestamp;
      Pose3D pose;
    };
};
