// pointcloud.idl
module PointCloudData {

    struct PointField {
        string name;
        unsigned long offset;
        unsigned long datatype;
        unsigned long count;
    };

    struct PointCloud2 {
        double timestamp; // time in seconds
        string frame_id;
        unsigned long height;
        unsigned long width;
        sequence<PointField> fields;
        boolean is_bigendian;
        unsigned long point_step;
        unsigned long row_step;
        sequence<uint8> data;
        boolean is_dense;
    };

    struct Point {
        float x;
        float y;
        float z;
        float intensity;  // optional
    };

};
