// pointcloud.idl
#include "Pose3d.idl"
module PointCloudData {

    struct PointField {
        string name;
        unsigned long offset;
        unsigned long datatype;
        unsigned long count;
    };

    struct PointCloud2 {
        double timestamp; // time in seconds
        string frame_id;
        unsigned long height;
        unsigned long width;
        sequence<PointField> fields;
        boolean is_bigendian;
        unsigned long point_step;
        unsigned long row_step;
 //       sequence<unsigned char> data;
        sequence<uint8> data;
        boolean is_dense;
    };

    struct Point {
        float x;
        float y;
        float z;
        float intensity;  // optional
    };

    struct Submap{
      unsigned long submap_id;
      Geometry::Pose3D submap_pose;
    };
    
    struct SubmapData {
      unsigned long submap_id;
      Geometry::Pose3D pose;
      PointCloud2 pointcloud;
    };

    struct SubmapList {
      sequence<Submap> submap_list;
    };
};
